genome:
  files:
    dataset_files: "defaults/genome_dataset"
    reference: "defaults/reference_genome.gb"
    clades: "defaults/clades_genome.tsv"
    auspice_config: "defaults/auspice_config_genome.json"
    colors: "defaults/colors.tsv"
  filter:
      exclude: "defaults/dropped_strains.txt"
      include: "defaults/include_strains.txt"
      group_by: "region"
      subsample_max_sequences: 800
      min_date: 1950
      min_length: 9000
  strain_id_field: "accession"
  genes: ['NSP', 'SP']
  export:
      metadata_columns: "strain division location"

